name: React

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm run build --if-present

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install eslint
      - run: npx eslint ./src

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install prettier
      - run: npx prettier --check ./src
