name: Rust

on:
  #push:
  #  branches: [ main ]
  pull_request:
    branches: 
      - main
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --verbose
    - run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy -- -D warnings

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: cargo tarpaulin --ignore-tests --verbose --all-features --workspace --timeout 120 --out Xml

      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true